### PR TITLE
Fixed a typo.

### PR DESCRIPTION
**Pull request by nirvdrum**
The diff is a bit ugly because it's all one big line.  I changed "it's" -> "its" when used as a possessive pronoun.

### CODE REVIEW

**Comment by indirect** [comment]
Thanks! :+1:

**Comment by nirvdrum** [comment]
No problem.  Thanks for all the hard work.

**Comment by segiddins** [comment]
This should've gone onto the bundler-site repo?

**Comment by indirect** [comment]
@segiddins lol yup. want to fix it there?

**Comment by nirvdrum** [comment]
Sorry.  So bundler.github.io is just generated from the bundler-site repo?

**Pull request merged**
